services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - monein

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: monein
      POSTGRES_USER: monein
      POSTGRES_PASSWORD: monein
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - monein

networks:
  monein:
    driver: bridge

volumes:
  db_data:
